shadow the phandle cache before free it in __of_free_phandle_cache()
Issue: LIN1018-3674

1/1 [
Author: Yue Tao
Email: Yue.Tao@windriver.com
Subject: of: shadow the phandle cache before free it in __of_free_phandle_cache()
Date: Mon, 18 Mar 2019 23:12:51 -0700

Upstream commit d7ba3e833 free phandle cache in a new function __of_free_phandle_cache(),
which conficts with the rt commit b75caf08, which free phandle cache outside of the devtree_lock.
To fix it, store the phandle cache in shadow before calling __of_free_phandle_cache().

drivers/of/base.c:120:2: error: 'shadow' undeclared (first use in this function)
  shadow = phandle_cache;
  ^~~~~~

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>