Failed to build nxp-imx6,7,8 BSPs: linux-yocto_4.18 failed (do_compile)
Issue: LIN1018-8790

1/5 [
Author: Jens Wiklander
Email: jens.wiklander@linaro.org
Subject: tee: handle lookup of shm with reference count 0
Date: Thu, 9 Dec 2021 15:59:37 +0100

commit 940e68e57ab69248fabba5889e615305789db8a7 from linux-stable
commit dfd0743f1d9ea76931510ed150334d571fbab49d upstream.

Since the tee subsystem does not keep a strong reference to its idle
shared memory buffers, it races with other threads that try to destroy a
shared memory through a close of its dma-buf fd or by unmapping the
memory.

In tee_shm_get_from_id() when a lookup in teedev->idr has been
successful, it is possible that the tee_shm is in the dma-buf teardown
path, but that path is blocked by the teedev mutex. Since we don't have
an API to tell if the tee_shm is in the dma-buf teardown path or not we
must find another way of detecting this condition.

Fix this by doing the reference counting directly on the tee_shm using a
new refcount_t refcount field. dma-buf is replaced by using
anon_inode_getfd() instead, this separates the life-cycle of the
underlying file from the tee_shm. tee_shm_put() is updated to hold the
mutex when decreasing the refcount to 0 and then remove the tee_shm from
teedev->idr before releasing the mutex. This means that the tee_shm can
never be found unless it has a refcount larger than 0.

Fixes: 967c9cca2cc5 ("tee: generic TEE subsystem")
Cc: stable@vger.kernel.org
Reviewed-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Reviewed-by: Lars Persson <larper@axis.com>
Reviewed-by: Sumit Garg <sumit.garg@linaro.org>
Reported-by: Patrik Lantz <patrik.lantz@axis.com>
[JW: backport to 4.19-stable]
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
[SG: backport of 940e68 from linux-4.19.y branch of linux-stable]
Signed-off-by: Stefan Ghinea <stefan.ghinea@windriver.com>
]

2/5 [
Author: Ovidiu Panait
Email: ovidiu.panait@windriver.com
Subject: Revert "tee: handle lookup of shm with reference count 0"
Date: Tue, 1 Feb 2022 16:55:58 +0200

This reverts commit 8206f0c803ad635afc27381fbce24489acb996b0.

Revert CVE-2021-44733 patchset, as it introduced the following build errors on
nxp-imx6/7/8:

work-shared/nxp-imx8/kernel-source/drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel_video_memory.c:2908:6:
error: 'struct dma_buf_ops' has no member named 'map_atomic'
|      .map_atomic = _dmabuf_kmap,
|       ^~~~~~~~~~

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
]

3/5 [
Author: Ovidiu Panait
Email: ovidiu.panait@windriver.com
Subject: Revert "dma-buf: remove kmap_atomic interface"
Date: Tue, 1 Feb 2022 16:59:34 +0200

This reverts commit 06cc2b2eb80421ffca039f7a1c7ea6e3737f9bc6.

Revert CVE-2021-44733 patchset, as it introduced the following build errors on
nxp-imx6/7/8:

work-shared/nxp-imx8/kernel-source/drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel_video_memory.c:2908:6:
error: 'struct dma_buf_ops' has no member named 'map_atomic'
|      .map_atomic = _dmabuf_kmap,
|       ^~~~~~~~~~

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
]

4/5 [
Author: Ovidiu Panait
Email: ovidiu.panait@windriver.com
Subject: Revert "dma-buf: make map_atomic and map function pointers optional"
Date: Tue, 1 Feb 2022 17:00:26 +0200

This reverts commit a7a64a818c60256340f7834f167d08f50af5df6c.

Revert CVE-2021-44733 patchset, as it introduced the following build errors on
nxp-imx6/7/8:

work-shared/nxp-imx8/kernel-source/drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel_video_memory.c:2908:6:
error: 'struct dma_buf_ops' has no member named 'map_atomic'
|      .map_atomic = _dmabuf_kmap,
|       ^~~~~~~~~~

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
]

5/5 [
Author: Jens Wiklander
Email: jens.wiklander@linaro.org
Subject: tee: handle lookup of shm with reference count 0
Date: Thu, 9 Dec 2021 15:59:37 +0100

commit dfd0743f1d9ea76931510ed150334d571fbab49d upstream.

Since the tee subsystem does not keep a strong reference to its idle
shared memory buffers, it races with other threads that try to destroy a
shared memory through a close of its dma-buf fd or by unmapping the
memory.

In tee_shm_get_from_id() when a lookup in teedev->idr has been
successful, it is possible that the tee_shm is in the dma-buf teardown
path, but that path is blocked by the teedev mutex. Since we don't have
an API to tell if the tee_shm is in the dma-buf teardown path or not we
must find another way of detecting this condition.

Fix this by doing the reference counting directly on the tee_shm using a
new refcount_t refcount field. dma-buf is replaced by using
anon_inode_getfd() instead, this separates the life-cycle of the
underlying file from the tee_shm. tee_shm_put() is updated to hold the
mutex when decreasing the refcount to 0 and then remove the tee_shm from
teedev->idr before releasing the mutex. This means that the tee_shm can
never be found unless it has a refcount larger than 0.

Fixes: 967c9cca2cc5 ("tee: generic TEE subsystem")
Cc: stable@vger.kernel.org
Reviewed-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Reviewed-by: Lars Persson <larper@axis.com>
Reviewed-by: Sumit Garg <sumit.garg@linaro.org>
Reported-by: Patrik Lantz <patrik.lantz@axis.com>
[JW: backport to 4.19-stable]
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
[OP: - backport of 940e68 from linux-4.19.y branch of linux-stable
     - adjusted context for 4.18
     - delete tee_shm_op_map_atomic() stub along with tee_shm_dma_buf_ops, as
       it was done for 4.14.y backport]
Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
]
Signed-off-by: Li Wang <li.wang@windriver.com>