ice: fix build errors when CONFIG_XDP_SOCKETS=y
Issue: LIN1019-6763

1/3 [
Author: Ovidiu Panait
Email: ovidiu.panait@windriver.com
Subject: Revert "ice: need_wakeup flag might not be set for Tx"
Date: Thu, 14 Oct 2021 16:10:02 +0000

This reverts commit 835e208bda692634aee93b1fc5daf687ca67e5df.

The ice ethernet driver in LTS19 was updated to the 5.12 codebase in
LINUXEXEC-10558 and adjusted to match various 5.2 APIs. It also added this
commit that relies on xsk_umem_uses_need_wakeup() API, which is not implemented
in 5.2 kernel. This currently causes the following build error when
CONFIG_XDP_SOCKETS=y:
drivers/net/ethernet/intel/ice/ice_xsk.c:941:6: error: implicit declaration of function 'xsk_umem_uses_need_wakeup' [-Werror=implicit-function-declaration]
|   941 |  if (xsk_umem_uses_need_wakeup(rx_ring->xsk_umem)) {
|       |      ^~~~~~~~~~~~~~~~~~~~~~~~~

To fix this, revert this commit, as the need_wakeup AF_XDP feature is not
implemented in 5.2.

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
]

2/3 [
Author: Ovidiu Panait
Email: ovidiu.panait@windriver.com
Subject: Revert "ice: Support XDP UMEM wake up mechanism"
Date: Thu, 14 Oct 2021 16:10:10 +0000

This reverts commit 2c318c554a703724b1c5eb6cc4a8b4635a6ef019.

The ice ethernet driver in LTS19 was updated to the 5.12 codebase in
LINUXEXEC-10558 and adjusted to match various 5.2 APIs. It also added this
commit that relies on xsk_umem_uses_need_wakeup() API, which is not implemented
in 5.2 kernel. This currently causes the following build error when
CONFIG_XDP_SOCKETS=y:
drivers/net/ethernet/intel/ice/ice_xsk.c:941:6: error: implicit declaration of function 'xsk_umem_uses_need_wakeup' [-Werror=implicit-function-declaration]
|   941 |  if (xsk_umem_uses_need_wakeup(rx_ring->xsk_umem)) {
|       |      ^~~~~~~~~~~~~~~~~~~~~~~~~

To fix this, revert this commit, as the need_wakeup AF_XDP feature is not
implemented in 5.2.

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
]

3/3 [
Author: Ovidiu Panait
Email: ovidiu.panait@windriver.com
Subject: ice: fix build errors when CONFIG_XDP_SOCKETS=y
Date: Thu, 14 Oct 2021 16:09:48 +0000

The ice ethernet driver in LTS19 was updated to the 5.12 codebase in
LINUXEXEC-10558 and adjusted to match various 5.2 APIs. When the kernel is
configured with CONFIG_XDP_SOCKETS=y, the build fails with the following errors:

1)
drivers/net/ethernet/intel/ice/ice_xsk.c:936:14: error: too few arguments to function 'ice_alloc_rx_bufs_zc'
|   936 |   failure = !ice_alloc_rx_bufs_zc(rx_ring, cleaned_count);
|       |

This was introduced by the backport of upstream commit [1]. Current codebase
still makes use of the ice_alloc_rx_bufs_fast_zc() interface that was later
removed, so use this instead of the ice_alloc_rx_bufs_zc() call introduced
by [1].

2)
drivers/net/ethernet/intel/ice/ice_xsk.c:542:20: error: 'struct ice_rxq_stats' has no member named 'page_reuse_count'
|   542 |   rx_ring->rx_stats.page_reuse_count++;
|       |

In current codebase, ice_rxq_stats structure has no page_reuse_count member, so
remove this call.

[1] https://github.com/torvalds/linux/commit/5bb0c4b5eb61d939fed0b27d11fb91fb85769c9a

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>
]
Signed-off-by: Liu Haitao <haitao.liu@windriver.com>