arm-versatile-926ejs: preempt-rt: relocate definition of hrtimer_rt_defer()
1/1 [
Author: Michel Thebeau
Email: michel.thebeau@windriver.com
Subject: arm-versatile-926ejs: preempt-rt: relocate definition of hrtimer_rt_defer()
Date: Mon, 4 Mar 2013 12:50:11 -0500

kernel/hrtimer.c:1044:4: error: implicit declaration of function 'hrtimer_rt_defer
kernel/hrtimer.c:1406:12: error: static declaration of 'hrtimer_rt_defer' follows non-static declaration
kernel/hrtimer.c:1044:9: note: previous implicit declaration of 'hrtimer_rt_defer' was here

In kernel-cache commit 78feec1e049b3dd6c481b1a8d4abb800ccc0c8a0 we fixed
some merge breakage for preempt-rt in "kernel/hrtimer.c".  The buildall
found this additional problem for arm-versatile-926ejs-preempt-rt

hrtimer_rt_defer() is defined in an ifdef CONFIG_PREEMPT_RT_BASE block
and neutered in the #else.  So move the declaration of
hrtimer_rt_defer() out of the ifdef CONFIG_HIGH_RES_TIMERS block.

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>