US126062 Xilinx Zynq-7000 ZC706/702
Rally: US126062

1/25 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: arm: dts: zynq: enablement of coresight topology
Date: Mon, 2 Nov 2015 15:53:53 +0800

This patch is to build the coresight topology structure of zynq-7000
series according to the docs of coresight and userguide of zynq-7000.

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
(cherry picked from commit e112bc9fbe213052d7bfc045adad2b7899f67fab)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

2/25 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: arm: dts: zynq: active watchdog status explicitly
Date: Mon, 17 Dec 2018 08:51:37 +0800

The latest zc706 has transferred to this change, so we do the similar
updates as well.

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
(cherry picked from commit 4d34c7ab5d108e2da098968197bf5420ca48f426)
]

3/25 [
Author: Lars-Peter Clausen
Email: lars@metafoo.de
Subject: drm/bridge: adv7511: Enable SPDIF support
Date: Fri, 1 Sep 2017 14:08:36 +0200

This is work-in-progress. Breaks I2S support at the moment.

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
(cherry picked from commit 7d87d403f18b7a0f0ccbc9827932880fc03ff45b)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

4/25 [
Author: Zumeng Chen
Email: zumeng.chen@gmail.com
Subject: drm: introduce helper for accessing EDID blob in drm_connector structure
Date: Tue, 20 Nov 2018 14:06:55 +0800

commit 4a531879a607d9867038a6b0544a154f866c8b53 from
  https://github.com/analogdevicesinc/linux.git

There is a bunch of drivers that directly access edid_blob_ptr in
drm_connector_structure. This requires a cast and possibly a NULL ptr
check.

Wrap this in a common helper.

Signed-off-by: Andrea Merello <andrea.merello@gmail.com>
Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

5/25 [
Author: Zumeng Chen
Email: zumeng.chen@gmail.com
Subject: gpu: drm: implement HDMI feature base on codec adv7511
Date: Tue, 20 Nov 2018 14:35:58 +0800

This patch comes from analog-zynq-2018R2 branch:
  https://github.com/analogdevicesinc/linux.git

HDMI includes video and audio features, detail implement as below:
- update adv7511 node in dts file
- update HDMI video and audio node in dts file.
- update adv7511 codec driver
- add HDMI video driver
- add HDMI audio driver

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

6/25 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: gpu: drm: i2c: Updates on adv7511 with audio
Date: Thu, 6 Dec 2018 09:49:22 +0800

This patch comes from analog-zynq-2018R2 branch:
  https://github.com/analogdevicesinc/linux.git

HDMI includes video and audio features, detail implement as below:

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

7/25 [
Author: Zumeng Chen
Email: zumeng.chen@gmail.com
Subject: drm: adi_axi_hdmi: fix compiling error due to the different base
Date: Tue, 20 Nov 2018 15:05:17 +0800

drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_drv.c:41:15: error: 'drm_fb_cma_create' undeclared here (not in a function); did you mean 'drm_gem_cma_create'
  .fb_create = drm_fb_cma_create,
               ^~~~~~~~~~~~~~~~~
drm_fb_cma_create has been removed in 4.18 due to unused, so replace it with
drm_gem_fb_create.

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

8/25 [
Author: Lars-Peter Clausen
Email: lars@metafoo.de
Subject: dma: axi-dmac: Split too large segments
Date: Thu, 15 Dec 2016 11:31:20 +0100

The axi-dmac driver currently rejects transfers with segments that are
larger than what the hardware can handle.

Re-work the driver so that these large segments are split into multiple
segments instead where each segment is smaller or equal to the maximum
segment size.

This allows the driver to handle transfers with segments of arbitrary size.

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
(cherry picked from commit bb77292bfc3e4ad6834d2a078e09baa201955e45)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

9/25 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: dma: axi-dmac: integrate the test codes from SDKs
Date: Tue, 27 Nov 2018 14:12:39 +0800

Testing codes for axi-dmac from the following git repo.
  git clone https://github.com/analogdevicesinc/linux.git

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

10/25 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: dma: axi-dmac: Infer synthesis configuration parameters hardware
Date: Tue, 27 Nov 2018 15:07:45 +0800

This patch integrates all the changes from
  git clone https://github.com/analogdevicesinc/linux.git

Some synthesis time configuration parameters of the DMA controller can be
inferred from the hardware itself.

Use this information as it is more reliably than the information specified
in the devicetree which might be outdated if the HDL project got changed.

Deprecate the devicetree properties that can be inferred from the hardware
itself.

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

11/25 [
Author: Lars-Peter Clausen
Email: lars@metafoo.de
Subject: dma: axi-dmac: Sanity check memory mapped interface support
Date: Tue, 6 Feb 2018 14:51:18 +0100

The AXI-DMAC supports different types of interface for the data source and
destination ports. Typically one of those ports is a memory-mapped
interface while the other is some kind of streaming interface.

The information about which kind of interface is used for each port is
encoded in the devicetree.

It is also possible in the driver to detect whether a port supports
memory-mapped transfers or not. For streaming interfaces the address
register is read-only and will always return 0. So in order to check if a
port supports memory-mapped transfers write a non-zero value to the
corresponding address register and check that the value read-back is still
non zero.

This allows to detect mismatches between the devicetree description and the
actual hardware configuration.

Unfortunately it is not possible to autodetect the interface types since
there is no method to distinguish between the different streaming ports. So
the best thing that can be done is to error out when a memory mapped port
is described in the devicetree but none is detected in the hardware.

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
(cherry picked from commit 546ee78bcabc20b1ab119a49efe84a769c8cd069)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

12/25 [
Author: Lars-Peter Clausen
Email: lars@metafoo.de
Subject: dma: axi-dmac: Discover length alignment requirement
Date: Thu, 24 May 2018 09:18:11 +0200

Starting with version 4.1.a the AXI-DMAC is capable of reporting the
required length alignment.

The LSBs that are required to be set for alignment will always read back as
set from the transfer length register. It is not possible to clear them by
writing a 0. This means the driver can discover the length alignment
requirement by writing 0 to that register and reading back the value.

Since the DMA will support length alignment requirements that are different
from the address alignment requirement track both of them independently.

For older versions of the peripheral assume that the length alignment
requirement is equal to the address alignment requirement.

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
(cherry picked from commit d95bc0b93985fe2a043a7537837ed3f8ea3d1c7e)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

13/25 [
Author: Dragos Bogdan
Email: dragos.bogdan@analog.com
Subject: dma: axi-dmac: Enable DMA_INTERLEAVE capability
Date: Wed, 13 Jun 2018 18:51:05 +0300

Since device_prep_interleaved_dma() is already implemented, the
DMA_INTERLEAVE capability should be set.

Signed-off-by: Dragos Bogdan <dragos.bogdan@analog.com>
(cherry picked from commit 81b810593ebcf1a537042704c8363bbaafbcba0b)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

14/25 [
Author: Dragos Bogdan
Email: dragos.bogdan@analog.com
Subject: dma: axi-dmac: Add support for interleaved cyclic transfers
Date: Thu, 14 Jun 2018 10:20:05 +0300

An example when this mode can be enabled is where the controller
is used as a Video DMA.

Signed-off-by: Dragos Bogdan <dragos.bogdan@analog.com>
(cherry picked from commit 78f1a03268d1f739e5f94edb751ded19ff7d4d32)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

15/25 [
Author: Dragos Bogdan
Email: dragos.bogdan@analog.com
Subject: dma: axi-dmac: Enable FLAG_LAST independent of FLAG_CYCLIC
Date: Thu, 14 Jun 2018 11:07:55 +0300

An example when these two bits should be enabled simultaneously is
where the controller is used as a Video DMA and the TLAST signal acts
as an "end of frame" signal.

Signed-off-by: Dragos Bogdan <dragos.bogdan@analog.com>
(cherry picked from commit a288f0fe3d120bb04f15ed4b699a4eb1d4acf7fb)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

16/25 [
Author: Alexandru Ardelean
Email: alexandru.ardelean@analog.com
Subject: dma: axi-dmac: don't check the number of frames for alignment
Date: Tue, 4 Sep 2018 16:05:55 +0300

It doesn't look like the 2D transfers were used much, prior to commit
81b810593ebcf1a537042704c8363bbaafbcba0b, so this may have not received
much attention.

There is no requirement for Y_LENGTH to be aligned to the bus-width (or
anything). X_LENGTH is required to be aligned though.

So, we shouldn't check that the number of frames is aligned.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit 04231a9a3ff27630f3453b5feca197723a5f3e88)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

17/25 [
Author: Alexandru Ardelean
Email: alexandru.ardelean@analog.com
Subject: dma: axi-dmac: assign `copy_align` property
Date: Tue, 9 Oct 2018 10:54:49 +0300

The `copy_align` property is a generic property that describes alignment
for DMA memcpy & sg ops.
It serves mostly an informational purpose, and can be used in DMA tests, to
pass the info to know what alignment to expect.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit bc30b5245bc3634247d824935084d53b7b0ead62)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

18/25 [
Author: Alexandru Ardelean
Email: alexandru.ardelean@analog.com
Subject: dma: axi-dmac: populate residue info for completed xfers
Date: Wed, 3 Oct 2018 12:57:41 +0300

This change implements computing DMA residue information for transfers.

The way this is done, is to dequeue the partial transfers from the FIFO of
partial transfers, store the partial length to the correct segment &
descriptor, and compute the residue before submitting the DMA cookie to the
DMA framework.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit 31baa60b75629fe466ddf8c5cbd16b7156692358)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

19/25 [
Author: Alexandru Ardelean
Email: alexandru.ardelean@analog.com
Subject: dma: axi-dmac: terminate early DMA transfers after a partial one
Date: Fri, 16 Nov 2018 09:50:28 +0200

When we get a partial transfer, we should not submit any more segments to
the hardware, as the data it will get will be unused and will just do
unnecessary processing.

During the start of transfer, we check it there was a partial transfer in a
previous completed segment and add the TLAST flag to the next segment that
is about to be submitted.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit 70b6b10a3739e93ba3ae987459b972be7384cac2)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

20/25 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: clk: axi-clkgen: Always set all fractional power bits in fractional mode
Date: Tue, 27 Nov 2018 15:43:51 +0800

This patch integrates the below commits from
  git clone https://github.com/analogdevicesinc/linux.git

ea32a7c4 clk: axi-clkgen: Always set all fractional power bits in fractional mode
c9b34dbb clk: axi-clkgen: Set power bits for fractional mode
af9cddef clk: axi-clkgen: Add support for fractional dividers

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

21/25 [
Author: Andy Shevchenko
Email: andy.shevchenko@gmail.com
Subject: scatterlist: introduce sg_nents_for_dma() helper
Date: Fri, 21 Oct 2016 20:35:26 +0300

Sometimes the user needs to split each entry on the mapped scatter list
due to DMA length constrains. This helper returns a number of entities
assuming that each of them is not bigger than supplied maximum length.

Signed-off-by: Andy Shevchenko <andy.shevchenko@gmail.com>
(cherry picked from commit 414a555896b2abca3518c3c878f21e7b1ea95904)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

22/25 [
Author: Alexandru Ardelean
Email: alexandru.ardelean@analog.com
Subject: dmaengine: virt-dma: store result on dma descriptor
Date: Wed, 3 Oct 2018 11:07:30 +0300

This allows each virtual channel to store information about each transfer
that completed, i.e. which transfer succeeded (or which failed) and if
there was any residue data on each (completed) transfer.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit ba563f4260aedda73fa306f5ad03da9999ef5a3d)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

23/25 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: arch: arm: dts: zc702: add axi interfaces to support HDMI feature
Date: Thu, 19 Apr 2018 17:26:04 +0800

This patch partly comes from analog-zynq-2018R2 branch:
  https://github.com/analogdevicesinc/linux.git

And add the commons hardware features in as no adv7511.

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

24/25 [
Author: Limeng
Email: Meng.Li@windriver.com
Subject: arch: arm: dts: zc702 enable watchdog node and add reset-on-timeout property
Date: Mon, 21 May 2018 08:46:34 +0000

enable watchdog and reset-on-timeout

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

25/25 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: arch: arm: dts: zc706: add axi interfaces to support HDMI feature
Date: Fri, 27 Apr 2018 16:12:48 +0800

This patch partly comes from analog-zynq-2018R2 branch:
  https://github.com/analogdevicesinc/linux.git

And add the commons hardware features in as no adv7511, fixing the wrong
compatible property as well.

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]
Signed-off-by: Yue Tao <Yue.Tao@windriver.com>