roles: Enable static DRD mode for role switch in Intel platforms
Issue: LIN10-3718

1/18 [
Author: Hans de Goede
Email: hdegoede@redhat.com
Subject: usb: roles: Add Intel xHCI USB role switch driver
Date: Tue, 20 Mar 2018 15:57:10 +0300

commit f6fb9ec02be1c1718596622263a88ff5490d2e95 upstream

Various Intel SoCs (Cherry Trail, Broxton and others) have an internal USB
role switch for swiching the OTG USB data lines between the xHCI host
controller and the dwc3 gadget controller.

Note on some Cherry Trail systems there is ACPI/AML code listening to
edge interrupts on the id-pin (through an _AIE ACPI method) and switching
the role between ROLE_HOST and ROLE_NONE based on the id-pin. Note it does
not set the role to ROLE_DEVICE, because device-mode is usually not used
under Windows.

The presence of AML code which modifies the cfg0 reg (on some systems)
means that our read/write/modify of cfg0 may race with the AML code
doing the same to avoid this we take the global ACPI lock while doing
the read/write/modify.

Signed-off-by: Hans de Goede <hdegoede@redhat.com>
Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

2/18 [
Author: Wei Yongjun
Email: weiyongjun1@huawei.com
Subject: usb: roles: Fix return value check in intel_xhci_usb_probe()
Date: Mon, 26 Mar 2018 06:43:57 +0000

commit 97eba3260e7c4e65e1c085301c2330110bd6aa2b upstream

In case of error, the function devm_ioremap_nocache() returns NULL
pointer not ERR_PTR(). The IS_ERR() test in the return value check
should be replaced with NULL test.

Fixes: f6fb9ec02be1 ("usb: roles: Add Intel xHCI USB role switch driver")
Signed-off-by: Wei Yongjun <weiyongjun1@huawei.com>
Reviewed-by: Hans de Goede <hdegoede@redhat.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

3/18 [
Author: Wei Yongjun
Email: weiyongjun1@huawei.com
Subject: usb: roles: Fix potential NULL dereference in intel_xhci_usb_probe()
Date: Thu, 29 Mar 2018 02:14:11 +0000

commit 548f4726a10568c208a7a9d676d66470e9e99aa3 upstream

platform_get_resource() may fail and return NULL, so we should
better check it's return value to avoid a NULL pointer dereference
a bit later in the code.

This is detected by Coccinelle semantic patch.

@@
expression pdev, res, n, t, e, e1, e2;
@@

res = platform_get_resource(pdev, t, n);
+ if (!res)
+   return -EINVAL;
... when != res == NULL
e = devm_ioremap_nocache(e1, res->start, e2);

Signed-off-by: Wei Yongjun <weiyongjun1@huawei.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

4/18 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: usb: roles: intel_xhci: Always allow user control
Date: Thu, 24 May 2018 11:18:24 +0300

commmit 35fcf02f801ba5358316113d0b94c541b9e39e84 upstream

Trying to determine the USB port type with this mux is very
difficult. To simplify the situation, always allow user
control, even if the port is USB Type-C port.

Reviewed-by: Hans de Goede <hdegoede@redhat.com>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

5/18 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: usb: roles: intel_xhci: Enable runtime PM
Date: Thu, 24 May 2018 11:18:27 +0300

commit cb296846860531defe93ebf75221e280970907f0 upstream

This fixes an issue where the mux does not get configured
when the parent device is suspended. The registers for this
mux are mapped to the parent device MMIO (usually xHCI PCI
device), so in order for the driver to be able to program
the registers, the parent device must be resumed.

Reported-by: Sathyanarayanan Kuppuswamy <sathyanarayanan.kuppuswamy@intel.com>
Fixes: f6fb9ec02be1 ("usb: roles: Add Intel xHCI USB role switch driver")
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

6/18 [
Author: Wan Ahmad Zainie
Email: wan.ahmad.zainie.wan.mohamad@intel.com
Subject: usb: roles: intel_xhci: Fix Unbalanced pm_runtime_enable
Date: Tue, 9 Oct 2018 12:52:47 +0800

commit 009b1948e153ae448f62f1887e2b58d0e05db51b upstream

Add missing pm_runtime_disable() to remove(), in order to avoid
an Unbalanced pm_runtime_enable when the module is removed and
re-probed.

Error log:
root@intel-corei7-64:~# modprobe -r intel_xhci_usb_role_switch
root@intel-corei7-64:~# modprobe intel_xhci_usb_role_switch
intel_xhci_usb_sw intel_xhci_usb_sw: Unbalanced pm_runtime_enable!

Fixes: cb2968468605 (usb: roles: intel_xhci: Enable runtime PM)
Cc: <stable@vger.kernel.org>
Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Wan Ahmad Zainie <wan.ahmad.zainie.wan.mohamad@intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

7/18 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: usb: common: Small class for USB role switches
Date: Tue, 20 Mar 2018 15:57:04 +0300

commit fde0aa6c175a4d8aa19e82b86ae0f9278bc8563b upstream

USB role switch is a device that can be used to choose the
data role for USB connector. With dual-role capable USB
controllers, the controller itself will be the switch, but
on some platforms the USB host and device controllers are
separate IPs and there is a mux between them and the
connector. On those platforms the mux driver will need to
register the switch.

With USB Type-C connectors, the host-to-device relationship
is negotiated over the Configuration Channel (CC). That
means the USB Type-C drivers need to be in control of the
role switch. The class provides a simple API for the USB
Type-C drivers for the control.

For other types of USB connectors (mainly microAB) the class
provides user space control via sysfs attribute file that
can be used to request role swapping from the switch.

Reviewed-by: Hans de Goede <hdegoede@redhat.com>
Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

8/18 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: usb: roles: Take care of driver module reference counting
Date: Wed, 19 Sep 2018 10:58:05 +0300

commit 5c54fcac9a9de559b444ac63ec3cd82f1d157a0b upstream

This fixes potential "BUG: unable to handle kernel paging
request at ..." from happening.

Fixes: fde0aa6c175a ("usb: common: Small class for USB role switches")
Cc: <stable@vger.kernel.org>
Acked-by: Hans de Goede <hdegoede@redhat.com>
Tested-by: Hans de Goede <hdegoede@redhat.com>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

9/18 [
Author: Arnd Bergmann
Email: arnd@arndb.de
Subject: usb: select USB_COMMON for usb role switch config
Date: Wed, 4 Apr 2018 14:21:53 +0200

commit 602f4fb71d2b4aa5a447d4ed25a58fd098df9058 upstream

The new axp288 extcon driver has no dependency on USB itself but
calls the usb role switch helper functions. This causes a link error
when USB_COMMON is disabled, as that subdirectory never gets entered:

drivers/extcon/extcon-axp288.o: In function `axp288_usb_role_work':
extcon-axp288.c:(.text+0x47b): undefined reference to `usb_role_switch_set_role'
extcon-axp288.c:(.text+0x498): undefined reference to `usb_role_switch_get_role'
drivers/extcon/extcon-axp288.o: In function `axp288_extcon_probe':
extcon-axp288.c:(.text+0x675): undefined reference to `usb_role_switch_get'
extcon-axp288.c:(.text+0x6d1): undefined reference to `usb_role_switch_put'
drivers/extcon/extcon-axp288.o: In function `axp288_put_role_sw':
extcon-axp288.c:(.text+0x1c): undefined reference to `usb_role_switch_put'

There are multiple ways of fixing this, I chose to 'select USB_COMMON',
since that is how we solved the same problem for other helpers like
USB_LED_TRIG or PHY drivers.

Fixes: d54f063cdbe4 ("extcon: axp288: Set USB role where necessary")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Hans de Goede <hdegoede@redhat.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

10/18 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: usb: roles: Add a description for the class to Kconfig
Date: Wed, 12 Dec 2018 20:13:55 +0300

commit c3788cd9963eb2e77de3c24142fb7c67b61f1a26 upstream

That makes the USB role switch support option visible and
selectable for the user. The class driver is also moved to
drivers/usb/roles/ directory.

This will fix an issue that we have with the Intel USB role
switch driver on systems that don't have USB Type-C connectors:

Intel USB role switch driver depends on the USB role switch
class as it should, but since there was no way for the user
to enable the USB role switch class, there was also no way
to select that driver. USB Type-C drivers select the USB
role switch class which makes the Intel USB role switch
driver available and therefore hides the problem.

So in practice Intel USB role switch driver was depending on
USB Type-C drivers.

Fixes: f6fb9ec02be1 ("usb: roles: Add Intel xHCI USB role switch driver")
Cc: <stable@vger.kernel.org>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

11/18 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: usb: roles: Find the muxes by also matching against the device node
Date: Wed, 13 Feb 2019 10:45:54 +0300

commit ec69e9533c4879c81eb7122771792864eb49af35 upstream

When the connections are defined in firmware, struct
device_connection will have the fwnode member pointing to
the device node (struct fwnode_handle) of the requested
device, and the endpoint will not be used at all in that
case.

Acked-by: Hans de Goede <hdegoede@redhat.com>
Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
Reviewed-by: Jun Li <jun.li@nxp.com>
Tested-by: Jun Li <jun.li@nxp.com>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

12/18 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: drivers: base: Unified device connection lookup
Date: Tue, 20 Mar 2018 15:57:02 +0300

commit f2d9b66d84f3ff5ea3aff111e6a403e04fa8bf37 upstream

Several frameworks - clk, gpio, phy, pmw, etc. - maintain
lookup tables for describing connections and provide custom
API for handling them. This introduces a single generic
lookup table and API for the connections.

The motivation for this commit is centralizing the
connection lookup, but the goal is to ultimately extract the
connection descriptions also from firmware by using the
fwnode_graph_* functions and other mechanisms that are
available.

Reviewed-by: Hans de Goede <hdegoede@redhat.com>
Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

13/18 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: device connection: Add fwnode member to struct device_connection
Date: Wed, 13 Feb 2019 10:45:52 +0300

commit 09aa11cfda9d8186046bcd1adcd6498b688114f4 upstream

This will prepare the device connection API for connections
described in firmware.

Acked-by: Hans de Goede <hdegoede@redhat.com>
Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
Reviewed-by: Jun Li <jun.li@nxp.com>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

14/18 [
Author: Mathias Nyman
Email: mathias.nyman@linux.intel.com
Subject: xhci: Add option to get next extended capability in list by passing id = 0
Date: Tue, 20 Mar 2018 15:57:08 +0300

commit d0a0fa9d74b9ba3b24b43fd50c318c27dc34c06f upstream

Modify xhci_find_next_ext_cap(base, offset, id) to return the next
capability offset if 0 is passed for id. Otherwise it will behave as
previously and return the offset of the next capability with matching id

capability id 0 is not used by xHCI (reserved)

This is useful when we want to loop through all capabilities.

Signed-off-by: Mathias Nyman <mathias.nyman@linux.intel.com>
Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

15/18 [
Author: Hans de Goede
Email: hdegoede@redhat.com
Subject: xhci: Add Intel extended cap / otg phy mux handling
Date: Tue, 20 Mar 2018 15:57:09 +0300

commit fa31b3cb2ae143aa6e26974fcbe75689da60bdbe upstream

The xHCI controller on various Intel SoCs has an extended cap mmio-range
which contains registers to control the muxing to the xHCI (host mode)
or the dwc3 (device mode) and vbus-detection for the otg usb-phy.

Having a role-sw driver included in the xHCI code (under drivers/usb/host)
is not desirable. So this commit adds a simple handler for this extended
capability, which creates a platform device with the caps mmio region as
resource, this allows us to write a separate platform role-sw driver for
the role-switch.

Note this commit adds a call to the new xhci_ext_cap_init() function
to xhci_pci_probe(), it is added here because xhci_ext_cap_init() must
be called only once. If in the future we also want to handle ext-caps
on non pci xHCI HCDs from xhci_ext_cap_init() a call to it should also
be added to other bus probe paths.

Signed-off-by: Hans de Goede <hdegoede@redhat.com>
Acked-by: Mathias Nyman <mathias.nyman@linux.intel.com>
Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
[Yongxin Liu: adjust context to backport to 4.12.29]
Integrated-by: Yongxin Liu <yongxin.liu@windriver.com>
]

16/18 [
Author: Heikki Krogerus
Email: heikki.krogerus@linux.intel.com
Subject: usb: xhci: pci: Enable Intel USB role mux on Apollo Lake platforms
Date: Mon, 1 Oct 2018 18:53:05 +0300

commit c02588a352defaf985fc1816eb6232663159e1b8 upstream

Intel Apollo Lake has the same internal USB role mux as
Intel Cherry Trail.

Cc: <stable@vger.kernel.org>
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
[Yongxin Liu: adjust context to backport to 4.12.29]
Integrated-by: Yongxin Liu <yongxin.liu@windriver.com>
]

17/18 [
Author: Saranya Gopal
Email: saranya.gopal@intel.com
Subject: xhci-ext-caps.c: Add property to disable SW switch
Date: Fri, 5 Oct 2018 15:19:47 +0530

In platforms like Cherrytrail, 'SW switch enable' bit
should not be enabled for role switch. This patch
adds a property to Intel USB Role Switch platform driver
to denote that SW switch should be disabled in
Cherrytrail devices.

Signed-off-by: Saranya Gopal <saranya.gopal@intel.com>
Signed-off-by: M, Balaji <m.balaji@intel.com>
[ heikki: fixed compile warnings ]
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
[Yongxin Liu: Patch is taken from
https://github.com/clearlinux-pkgs/linux-iot-lts2018.git]
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

18/18 [
Author: Saranya Gopal
Email: saranya.gopal@intel.com
Subject: roles: Enable static DRD mode for role switch in Intel platforms
Date: Fri, 5 Oct 2018 15:20:15 +0530

Enable static DRD mode in Intel platforms which guarantees
successful role switch all the time. This fixes issues like
software role switch failure after cold boot and issue with
role switch when 3.0 OTG cable is used. But, do not enable
static DRD mode for Cherrytrail devices which rely on firmware
for role switch.

Signed-off-by: Saranya Gopal <saranya.gopal@intel.com>
Signed-off-by: M, Balaji <m.balaji@intel.com>
[ heikki: Minor cleanup ]
Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
[Yongxin Liu: Patch is tasken from
https://github.com/clearlinux-pkgs/linux-iot-lts2018.git]
Signed-off-by: Yongxin Liu <yongxin.liu@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>