ocf: import latest version of ocf-linux-20120127
1/5 [
Author: Michel Thebeau
Email: michel.thebeau@windriver.com
Subject: ocf: import latest version of ocf-linux-20120127
Date: Thu, 14 Jun 2012 16:34:19 -0400

Importing OCF-linux to wrlinux for inclusion in standard kernel.

Source: OCF-linux ocf-linux-20120127.tar.gz
        http://sourceforge.net/projects/ocf-linux/files/ocf-linux/20120127/
        http://ocf-linux.sourceforge.net/

For kernel patch instructions and generation information see "Adding OCF
to linux source" section of the ocf README.

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

2/5 [
Author: Michel Thebeau
Email: michel.thebeau@windriver.com
Subject: ocf: OCF_CRYPTOSOFT depends on CRYPTO_HASH2
Date: Mon, 25 Jun 2012 13:23:10 -0400

ERROR: "crypto_alloc_ahash" [crypto/ocf/cryptosoft.ko] undefined!
ERROR: "crypto_alloc_ablkcipher" [crypto/ocf/cryptosoft.ko] undefined!
ERROR: "crypto_ahash_digest" [crypto/ocf/cryptosoft.ko] undefined!
ERROR: "crypto_ahash_setkey" [crypto/ocf/cryptosoft.ko] undefined!

These are defined in crypto/ahash.c, which is enabled by CRYPTO_HASH2.

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

3/5 [
Author: Michel Thebeau
Email: michel.thebeau@windriver.com
Subject: ocf: drop if IRQ_NONE handling old kernel versions
Date: Thu, 21 Jun 2012 16:28:10 -0400

include/linux/irqreturn.h:11:12: error: expected identifier before '=' token
include/linux/irqreturn.h:16:24: error: two or more data types in declaration specifiers
include/linux/irqreturn.h:16:14: warning: empty declaration with storage class specifier does not redeclare tag [enabled by default]
include/linux/irqreturn.h:17:0: warning: "IRQ_RETVAL" redefined [enabled by default]
crypto/ocf/ocf-compat.h:212:0: note: this is the location of the previous definition

Per the comment in crypto/ocf/ocf-compat.h, there are no older kernel
versions; we are running 3.4.x.

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

4/5 [
Author: Yang Shi
Email: yang.shi@windriver.com
Subject: ocf: Make ocf session and cselist operation SMP safe
Date: Mon, 6 Aug 2012 16:10:42 -0700

Add two spin locks, session_lock and cselist_lock, to make
newsession/freesession and cse list operation (add/delete/find)
SMP safe.

Signed-off-by: Yang Shi <yang.shi@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

5/5 [
Author: Michel Thebeau
Email: michel.thebeau@windriver.com
Subject: OCF/random: update use of mix_pool_bytes() function
Date: Tue, 4 Sep 2012 14:21:15 -0400

commit e0604ba541f04a542ee9a7f6a468a60688ad8c72 in Linux 3.4.9 adds an
out parameter to mix_pool_bytes().  The out is not required.

Signed-off-by: Michel Thebeau <michel.thebeau@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>