Buildissue: build guest qemu failed kernel/power/suspend.c:100:2: error: implicit declaration of function 'rawspin_unlock_irq'
Issue: LIN10-4089

1/1 [
Author: Jiping Ma
Email: jiping.ma2@windriver.com
Subject: Buildissue: build guest qemu failed kernel/power/suspend.c:100:2: error: implicit declaration of function 'rawspin_unlock_irq'
Date: Thu, 14 Jun 2018 09:48:20 +0000

commit [0d29972245] introduced the breakage.

Signed-off-by: Jiping Ma <jiping.ma2@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>