drm: xilinx: explicitly destroy connector when shutdown
Rally: US110517

1/5 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: ethernet: xilinx: TSN: fix compiling error when uprev to 4.12
Date: Tue, 10 Apr 2018 08:04:54 +0800

It seems module and of related header dependencies have been re-constructed, so
we explicitly include these two header to avoid the following errors:

drivers/net/ethernet/xilinx/xilinx_tsn_switch.c:67:1: warning: data definition has no type or storage class
 MODULE_DEVICE_TABLE(of, tsnswitch_of_match);
 ^~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/xilinx/xilinx_tsn_switch.c:67:1: error: type defaults to 'int' in declaration of 'MODULE_DEVICE_TABLE' [-Werror=implicit-int]
drivers/net/ethernet/xilinx/xilinx_tsn_switch.c:67:1: warning: parameter names (without types) in function declaration
In file included from include/linux/dmaengine.h:20:0,
                 from include/linux/netdevice.h:38,
                 from drivers/net/ethernet/xilinx/xilinx_axienet.h:11,
                 from drivers/net/ethernet/xilinx/xilinx_tsn_switch.h:21,
                 from drivers/net/ethernet/xilinx/xilinx_tsn_switch.c:18:
include/linux/device.h:1477:1: warning: data definition has no type or storage class
 module_init(__driver##_init); \
 ^
include/linux/platform_device.h:228:2: note: in expansion of macro 'module_driver'
  module_driver(__platform_driver, platform_driver_register, \
  ^~~~~~~~~~~~~
drivers/net/ethernet/xilinx/xilinx_tsn_switch.c:791:1: note: in expansion of macro 'module_platform_driver'
 module_platform_driver(tsnswitch_driver);
 ^~~~~~~~~~~~~~~~~~~~~~
include/linux/device.h:1477:1: error: type defaults to 'int' in declaration of 'module_init' [-Werror=implicit-int]
 module_init(__driver##_init); \
 ^
include/linux/platform_device.h:228:2: note: in expansion of macro 'module_driver'
  module_driver(__platform_driver, platform_driver_register, \
  ^~~~~~~~~~~~~
drivers/net/ethernet/xilinx/xilinx_tsn_switch.c:791:1: note: in expansion of macro 'module_platform_driver'
 module_platform_driver(tsnswitch_driver);
 ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

2/5 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: v4l: xilinx: csi2rxss: replace media_entity_init with media_entity_pads_init
Date: Mon, 9 Apr 2018 15:48:15 +0800

This patch is to fix a compiling error according to the mainline commit ab22e77c
as follows:

drivers/media/platform/xilinx/xilinx-csi2rxss.c: In function 'xcsi2rxss_probe':
drivers/media/platform/xilinx/xilinx-csi2rxss.c:1638:8: error: implicit declaration of function 'media_entity_init';
|   ret = media_entity_init(&subdev->entity, 2, xcsi2rxss->pads, 0);
|         ^~~~~~~~~~~~~~~~~

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

3/5 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: pll: zynqmp: add support for the disable for pll
Date: Mon, 9 Apr 2018 09:59:36 +0800

This commit 8001b6da comes from:
  https://github.com/Xilinx/linux-xlnx.git

As the part of changing frequency for DP through VPLL reset is the part
of programming sequence as to do a reset.

This is the sequence from TRM describing APLL:
APLL Clock Generation Sequence: Integer Multipliers and Dividers
This example assumes the input PS_REF_CLK frequency is 50 MHz, the FBDIV
value is 40, and
the output divider is turned on. The output clock is calculated to be
50 MHz x 40/2 = 1000 MHz. For a new frequency of 1600 MHz, the FBDIV
value is switched
to 32 and the output divider is turned off. This example uses the APLL.
Note: Before redoing the PLL clock output frequency, check that the
downstream clocks are in a safe
zone before releasing. For instance, if the APU DIVISOR is set to 2.
1. Set the new FBDIV, CLKOUT value (do not modify other values in the
APLL_CTRL
register).
APLL_CTRL[DIV2] = 0, APLL_CTRL[FBDIV] = 0x20 (APL_CTRL ≤ 0x0000_2000)
2. Set the helper data for APLL_CFG using the helper data in Table 37-5.
3. Set the bypass.
APLL_CTRL[BYPASS] = 1’b1 (APL_CTRL ≤ 0x0000_2008)
4. Assert reset. This is when the new data is actually captured into the
PLL.
APLL_CTRL[RESET] = 1’b1 (APL_CTRL ≤ 0x0000_2009)
5. Deassert reset.
APLL_CTRL[RESET] = 1’b0 (APL_CTRL ≤ 0x0000_2008)
6. Check for LOCK. Wait until: PLL_STATUS [APLL_LOCK] = 1’b1
7. Deassert bypass.
APLL_CTRL[BYPASS] = 1’b0 (APL_CTRL ≤ 0x0000_2000)
The PLL usable clock is set to 1600 MHz.

Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

4/5 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: drm: xilinx: xilinx_drm_fb: initialize properly drm_format_info
Date: Sun, 8 Apr 2018 10:48:35 +0800

Since drm_format_info is constant, we use drm_format_info to initialize it
as other drm drivers in mainline to avoid the following code walking error:

Unable to handle kernel write to read-only memory at virtual address ffffff8008ab3f10
pgd = ffffffc877e59000
[ffffff8008ab3f10] *pgd=0000000877f99003, *pud=0000000877f99003, *pmd=0000000000000000
Internal error: Oops: 9600004f [#1] PREEMPT SMP
Modules linked in: mali(O) openvswitch nf_defrag_ipv6 nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack libcrc32c
CPU: 2 PID: 700 Comm: Xorg Tainted: G           O    4.12.21-yocto-standard #1
Hardware name: ZynqMP ZCU102 Rev1.0 (DT)
         task: ffffffc8799eb200 task.stack: ffffffc876424000
PC is at xilinx_drm_fb_create+0x118/0x1f0
LR is at xilinx_drm_fb_create+0x110/0x1f0
Starting Hostname Service...
pc : [<ffffff8008646650>] lr : [<ffffff8008646648>] pstate: 60000145
sp : ffffffc876427b40
x29: ffffffc876427b40 x28: 000000000017f800
x27: ffffffc877c96800 x26: ffffffc876427bc0
x25: ffffffc877eed200 x24: ffffffc876427cac
x23: 0000000000000001 x22: 0000000000000400
x21: ffffffc876427c98 x20: ffffffc879262b00
x19: 0000000000000001 x18: 00000000000000be
x17: 0000007f7cd1fe10 x16: ffffff800822f010
x15: 0000007f7cffbb00 x14: 0400000000000001
x13: 0000000000000300 x12: 0000000000000400
x11: 00000000ffffffff x10: 0000000000000001
x9 : 0000000000000040 x8 : 0000000000000000
x7 : ffffffc879510920 x6 : ffffffc879262b18
x5 : 0000000000000000 x4 : 0000000000000000
x3 : 0000000000000010 x2 : ffffff8008ab3f0c
x1 : 0000000000000010 x0 : 0000000000000010
Process Xorg (pid: 700, stack limit = 0xffffffc876424000)
Stack: (0xffffffc876427b40 to 0xffffffc876428000)
Call trace:
Exception stack(0xffffffc876427970 to 0xffffffc876427aa0)
7960:                                   0000000000000001 0000008000000000
7980: ffffffc876427b40 ffffff8008646650 0000000000000000 ffffff8008dc9000
79a0: ffffffc876427af0 ffffffc8799eb758 ffffffc876427a00 ffffff8008518630
79c0: ffffffc879510920 ffffffc879af8280 ffffffc876427a20 ffffff8008518630
79e0: ffffffc879510920 ffffffc879af8280 0000000000000000 0000000000000000
7a00: ffffffc879af82b0 ffffffc876427cac 0000000000000010 0000000000000010
7a20: ffffff8008ab3f0c 0000000000000010 0000000000000000 0000000000000000
7a40: ffffffc879262b18 ffffffc879510920 0000000000000000 0000000000000040
7a60: 0000000000000001 00000000ffffffff 0000000000000400 0000000000000300
7a80: 0400000000000001 0000007f7cffbb00 ffffff800822f010 0000007f7cd1fe10
[<ffffff8008646650>] xilinx_drm_fb_create+0x118/0x1f0
[<ffffff80086381f0>] drm_internal_framebuffer_create+0x298/0x468
[<ffffff8008638400>] drm_mode_addfb2+0x40/0xc0
[<ffffff800863850c>] drm_mode_addfb+0x8c/0xa8
[<ffffff80086205b0>] drm_ioctl+0x190/0x448
[<ffffff800822e990>] do_vfs_ioctl+0xb0/0x730
[<ffffff800822f09c>] SyS_ioctl+0x8c/0xa8
[<ffffff8008083730>] el0_svc_naked+0x24/0x28
Code: 9101f3a1 97fffaf3 f9401e82 294f0fa1 (39001

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

5/5 [
Author: Zumeng Chen
Email: zumeng.chen@windriver.com
Subject: drm: xilinx: explicitly destroy connector when shutdown
Date: Sun, 8 Apr 2018 15:34:19 +0800

SDK didn't have a mechanism to auto free connector, so we workaround it
by mannually to avoid a kernel warning when machine shutdown as follows:

------------[ cut here ]------------
WARNING: CPU: 0 PID: 1 at drivers/gpu/drm/drm_mode_config.c:458 drm_mode_config_cleanup+0x240/0x260
Modules linked in: mali(O) openvswitch nf_defrag_ipv6 nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack libcrc32c
CPU: 0 PID: 1 Comm: systemd-shutdow Tainted: G      D W  O    4.12.21-yocto-standard #1
Hardware name: ZynqMP ZCU102 Rev1.0 (DT)
task: ffffffc87b160000 task.stack: ffffffc87b13c000
PC is at drm_mode_config_cleanup+0x240/0x260
LR is at drm_mode_config_cleanup+0x154/0x260
pc : [<ffffff800863f4d0>] lr : [<ffffff800863f3e4>] pstate: 20000145
sp : ffffffc87b13fc30
x29: ffffffc87b13fc30 x28: ffffffc87b160000
x27: ffffff8008a32000 x26: 000000000000008e
x25: ffffff8008c11f80 x24: ffffff8008ed7040
x23: ffffffc87b3d5870 x22: ffffff8008f75000
x21: ffffffc879af82d8 x20: ffffffc879af83e8
x19: ffffffc879af8000 x18: 0000000000000024
x17: 0000000000000000 x16: 0000000000000000
x15: 0000000000000000 x14: ffffffc879510a68
x13: ffffffc879af8280 x12: ffffffc879510920
x11: 0000000000000000 x10: 0000000000000000
x9 : 0000000000000040 x8 : 0000000000000001
x7 : 0000000000000228 x6 : 000000000000000f
x5 : ffffff800863c2c8 x4 : 0000000000000000
x3 : ffffffc877eece00 x2 : ffffffbf21dfbb10
x1 : ffffffc879af8410 x0 : ffffffc879262b08
---[ end trace e06d0f4a43765e6d ]---
Call trace:
Exception stack(0xffffffc87b13fa60 to 0xffffffc87b13fb90)
fa60: ffffffc879af8000 0000008000000000 ffffffc87b13fc30 ffffff800863f4d0
fa80: ffffffc877eece00 ffffff800863c2c8 0000000000003788 ffffffc87b003980
faa0: 00000048771b3000 000000000000008e ffffff8008a32000 ffffffc87b160000
fac0: ffffffc879add600 ffffff80086280cc 0000000000030068 ffffffc877eece00
fae0: 00000048771b3000 000000000000008e ffffffc87b13fb40 0000000180100003
fb00: ffffffc879262b08 ffffffc879af8410 ffffffbf21dfbb10 ffffffc877eece00
fb20: 0000000000000000 ffffff800863c2c8 000000000000000f 0000000000000228
fb40: 0000000000000001 0000000000000040 0000000000000000 0000000000000000
fb60: ffffffc879510920 ffffffc879af8280 ffffffc879510a68 0000000000000000
fb80: 0000000000000000 0000000000000000
[<ffffff800863f4d0>] drm_mode_config_cleanup+0x240/0x260
[<ffffff8008644c8c>] xilinx_drm_unload+0x4c/0x58
[<ffffff8008624a64>] drm_dev_unregister+0x44/0xe0
[<ffffff8008624c7c>] drm_put_dev+0x3c/0x78
[<ffffff8008644b94>] xilinx_drm_platform_shutdown+0x24/0x30
[<ffffff800865845c>] platform_drv_shutdown+0x2c/0x38
[<ffffff8008653e18>] device_shutdown+0x180/0x200
[<ffffff80080c513c>] kernel_halt+0x3c/0x68
[<ffffff80080c5414>] SyS_reboot+0x1d4/0x1f0
[<ffffff8008083730>] el0_svc_naked+0x24/0x28
reboot: System halted

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>