iio: adc: imx8qxp_adc: fix build error
Issue: LIN1018-5911

1/1 [
Author: Wenlin Kang
Email: wenlin.kang@windriver.com
Subject: iio: adc: imx8qxp_adc: fix build error.
Date: Fri, 3 Apr 2020 15:31:10 +0000

iio_info.driver_module has been droped with commit 97623c0a80a6(iio: drop
iio_info.driver_module and iio_trigger_ops.owner.), so here should remove
it from imx8qxp_adc_iio_info too.

This fixes:
drivers/iio/adc/imx8qxp_adc.c:501:3: error: 'const struct iio_in
   .driver_module = THIS_MODULE,
    ^~~~~~~~~~~~~

Signed-off-by: Wenlin Kang <wenlin.kang@windriver.com>
]
Signed-off-by: Yue Tao <Yue.Tao@windriver.com>