NXP i.MX8
Issue: LINUXPG-22

1/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: ARM64: DMA: fix compile error for swiotlb_dma_ops.dma_supported
Date: Thu, 4 Apr 2019 11:07:43 +0800

In upstream commit b7da40949ec5 ("arm64: rename swiotlb_dma_ops"),
swiotlb_dma_ops in dma-mapping.c has been renamed to arm64_swiotlb_dma_ops,
so __swiotlb_dma_supported_quirk should be assigned to
arm64_swiotlb_dma_ops.dma_supported but not swiotlb_dma_ops.dma_supported.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

2/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: cpufreq: imx8: delete validation of the frequency table from ->init()
Date: Thu, 4 Apr 2019 13:45:55 +0800

In upstream commit d417e0691ac0 ("cpufreq: Validate frequency table in the core"),
validation of the frequency table has been moved in the cpufreq core, then in
upstream commit 2dd0df8472ff ("cpufreq: Drop cpufreq_table_validate_and_show()"),
the function is dropped. So just set policy->freq_table field directly.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

3/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: cpufreq: imx8: pass correct argument to of_cpufreq_cooling_register
Date: Thu, 4 Apr 2019 14:32:01 +0800

In upstream commit f5f263fed66f ("cpu_cooling: Make of_cpufreq_power_cooling_register()
parse DT"), the operation of parse DT has been moved to of_cpufreq_power_cooling_register.

And in upstream commit 3ebb62ffc4e4 ("cpu_cooling: Keep only one of_cpufreq*cooling_register()
helper"), of_cpufreq_power_cooling_register has been renamed to of_cpufreq_cooling_register,
so now of_cpufreq_cooling_register not need the argument "np" anymore.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

4/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: gpio: gpio-mxc: fix compile error
Date: Thu, 4 Apr 2019 15:45:15 +0800

Fix compile error which caused by modification in the wrong line.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

5/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: drm/imx/dcss: use drm_property_blob_put instead of drm_property_unreference_blob
Date: Thu, 4 Apr 2019 16:42:29 +0800

In upstream commit 3ae7fb202d86 ("drm: Remove drm_property_{un/reference}_blob aliases"),
the function "drm_property_unreference_blob" has been deleted and use drm_property_blob_put
instead.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

6/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: drm/imx/dcss: use drm_gem_fb_prepare_fb() instead of drm_fb_cma_prepare_fb
Date: Thu, 4 Apr 2019 16:56:57 +0800

In upstream commit c0f095f76698 ("drm/fb-cma-helper: Remove unused functions"),
drm_fb_cma_prepare_fb is substituted for drm_gem_fb_prepare_fb, and
drm_fb_cma_create has been substituted for drm_gem_fb_create.

Because of upstream commit 29ad20b22c8f ("drm: Add drm_device->fb_helper pointer"),
drm_device holds a pointer to the drm_fb_helper structure. This means that the driver
doesn't have to keep track of that. Also use the drm_fb_helper functions directly.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

7/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: drm/imx/hdp: drop redundant drm_edid_to_eld() call in imx-hdp.c
Date: Mon, 8 Apr 2019 14:10:44 +0800

According to upstream commit d471ed04b487 ("drm/drivers: drop
redundant drm_edid_to_eld() calls"), remove drm_edid_to_eld.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

8/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: drm/imx/dcss: use new name HDMI_EXTENDED_COLORIMETRY_OPRGB
Date: Thu, 4 Apr 2019 16:46:36 +0800

In upstream commit 391d6f13307e ("media: hdmi.h: rename ADOBE_RGB
to OPRGB and ADOBE_YCC to OPYCC"), HDMI_EXTENDED_COLORIMETRY_ADOBE_RGB
has been renamed to HDMI_EXTENDED_COLORIMETRY_OPRGB.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

9/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: drm/imx/hdp: fix drm_hdmi_vendor_infoframe_from_display_mode compile error
Date: Mon, 8 Apr 2019 14:21:55 +0800

In upstream commit f1781e9bb2dd ("drm/edid: Allow HDMI infoframe without
VIC or S3D"), drm_hdmi_vendor_infoframe_from_display_mode increases an
argument "struct drm_connector *connector", so add it to imx-hdmi.c

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

10/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: drm/imx/imx-drm-core: fix imxdrm missing compile error
Date: Mon, 8 Apr 2019 14:32:10 +0800

Adding imxdrm definition back to imx_drm_unbind function
to avoid compiling error.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

11/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: drm/bridge: nwl-dsi: fix compile error
Date: Thu, 4 Apr 2019 16:32:21 +0800

In upstream commit 9928688492ae ("drm/bridge: change return type
of drm_bridge_add function"), the function drm_bridge_add has no
return value anymore, so remove the return value of it to avoid
compile error.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

12/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: drm/imx/dcss: fix compile error in dcss-kms.c
Date: Thu, 4 Apr 2019 17:23:32 +0800

In upstream commit 77ac3b00b131 ("drm/atomic: Remove deprecated accessor macros"),
for_each_connector_in_state has been removed and should use for_each_new_connector_in_state
instead.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

13/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: gpu/imx/dcss: include linux/seq_file.h where needed
Date: Mon, 8 Apr 2019 14:51:47 +0800

The dcss-*.c need include this header implicitly to avoid
compile error as below:

error: implicit declaration of function 'seq_printf' [-Werror=implicit-function-declaration]

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

14/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: media: imx8: mxc-mipi-csi2_yav: fix compile error
Date: Tue, 9 Apr 2019 10:22:13 +0800

In upstream commit b6ee3f0dcf43 ("media: v4l: async: Move async subdev
notifier operations to a separate structure"), notifier.bound has been
moved into "struct v4l2_async_notifier_operations".

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

15/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: media: imx8: use new structure to avoid fwnode.fwnode
Date: Tue, 9 Apr 2019 10:00:42 +0800

In upstream commit 4e48afecd5ee ("media: v4l2-async: simplify
v4l2_async_subdev structure"), fwnode.fwnode is not needed anymore.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

16/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: mxc: sim: imx_emvsim: include header file explicitly to avoid compile error
Date: Wed, 10 Apr 2019 13:48:07 +0800

This patch fixes compiling error as below:
drivers/mxc/sim/imx_emvsim.c: In function ‘emvsim_suspend’:
drivers/mxc/sim/imx_emvsim.c:1587:2: error: implicit declaration of function ‘pinctrl_pm_select_sleep_state’ [-Werror=implicit-function-declaration]
  pinctrl_pm_select_sleep_state(&pdev->dev);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/mxc/sim/imx_emvsim.c: In function ‘emvsim_resume’:
drivers/mxc/sim/imx_emvsim.c:1601:2: error: implicit declaration of function ‘pinctrl_pm_select_default_state’ [-Werror=implicit-function-declaration]
  pinctrl_pm_select_default_state(&pdev->dev);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

17/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: extcon: ptn5150: fix compile error caused by implicit declaration of functions
Date: Thu, 4 Apr 2019 14:57:00 +0800

Because of upstream commit 176aa3601213 ("extcon: Split out extcon header
file for consumer and provider device"), the declaration of some functions
have been moved to extcon-provide.h.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

18/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: usb: dwc3: core: fix compile error
Date: Wed, 10 Apr 2019 15:08:43 +0800

In upstream commit 44feb8e6ea2d ("usb: dwc3: use local copy of
resource to fix-up register offset"), err0 has been removed and
we need return value directly.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

19/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: sound: imx-cdnhdmi: replace codec to component
Date: Thu, 11 Apr 2019 14:18:51 +0800

Because of upstream commit 999f7f5af8eb ("ASoC: remove Codec related code"),
the "struct snd_soc_codec" should be replaced with "struct snd_soc_component".

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

20/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: perf: ddr-perf: using get/put_cpu to fix preempt warning
Date: Mon, 15 Apr 2019 14:38:51 +0800

When booting kernel with DEBUG_PREEMPT enabled, it dumps the warning
as below:

BUG: using smp_processor_id() in preemptible [00000000] code: swapper/0/1
caller is debug_smp_processor_id+0x1c/0x28
CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.18.31-yocto-standard+ #462
Hardware name: Freescale i.MX8MQ EVK (DT)
Call trace:
 dump_backtrace+0x0/0x1d0
 show_stack+0x24/0x30
 dump_stack+0x8c/0xac
 check_preemption_disabled+0xf8/0x100
 debug_smp_processor_id+0x1c/0x28
 ddr_perf_probe+0x138/0x1f0
 platform_drv_probe+0x58/0xa8
 driver_probe_device+0x224/0x300
 __driver_attach+0xe4/0xe8
 bus_for_each_dev+0x84/0xd8
 driver_attach+0x30/0x40
 bus_add_driver+0x1c4/0x230
 driver_register+0x64/0x110
 __platform_driver_register+0x54/0x60
 imx_ddr_pmu_init+0x20/0x28
 do_one_initcall+0x68/0x258
 kernel_init_freeable+0x2e4/0x3e8
 kernel_init+0x18/0x110
 ret_from_fork+0x10/0x1c

This happens because smp_processor_id() is called in preempt enabled condition.
So use get/put_cpu to avoid it.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

21/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: Revert "MLK-18113: rpmsg: virtio_rpmsg_bus: fix rpmsg_probe() for virtio-mmio transport"
Date: Mon, 15 Apr 2019 15:22:52 +0800

This reverts commit 51d5c7a64236a7b35d0c58f3550310a2d83bb9cd.

When booting kernel with DEBUG_PREEMPT enabled, it dumps the
warning as below:
WARNING: CPU: 1 PID: 1 at ./include/linux/dma-mapping.h:516 rpmsg_probe+0x400/0x4f0
Modules linked in:
CPU: 1 PID: 1 Comm: swapper/0 Not tainted 4.18.31-yocto-standard+ #450
Hardware name: Freescale i.MX8MQ EVK (DT)
pstate: 20000005 (nzCv daif -PAN -UAO)
pc : rpmsg_probe+0x400/0x4f0
lr : rpmsg_probe+0x12c/0x4f0
sp : ffff00000803b7b0
x29: ffff00000803b7b0 x28: 0000000000000000
x27: 0000000000040000 x26: 0000000000040000
x25: ffff800078846010 x24: ffff800078930e40
x23: 0000000000000000 x22: ffff000008fb8000
x21: ffff0000090c78c8 x20: ffff000008bb7000
x19: ffff800078930e00 x18: ffffffffffffffff
x17: 0000000000000000 x16: 0000000000000000
x15: ffff000008fb8588 x14: ffff000008e23000
x13: ffff8000786c01a0 x12: 0000000000000000
x11: ffff8000bfffe008 x10: 0000fffff6f17840
x9 : 0000000000000000 x8 : ffff80007894b090
x7 : 0000000000000000 x6 : 000000000000003f
x5 : 0000000000000040 x4 : fffffffffffffff0
x3 : 0000000000000001 x2 : 0000000000000000
x1 : 0000000000000200 x0 : 0000000000000000
Call trace:
 rpmsg_probe+0x400/0x4f0
 virtio_dev_probe+0x168/0x210
 driver_probe_device+0x224/0x300
 __device_attach_driver+0xa0/0xe8
 bus_for_each_drv+0x74/0xd8
 __device_attach+0xe0/0x138
 device_initial_probe+0x24/0x30
 bus_probe_device+0x9c/0xa8
 device_add+0x3d4/0x5f0
 register_virtio_device+0xf0/0x108
 imx_rpmsg_probe+0x430/0x5b8
 platform_drv_probe+0x58/0xa8
 driver_probe_device+0x224/0x300
 __driver_attach+0xe4/0xe8
 bus_add_driver+0x1c4/0x230
 driver_register+0x64/0x110
 __platform_driver_register+0x54/0x60
 imx_rpmsg_init+0x24/0x58
 do_one_initcall+0x68/0x258
 kernel_init_freeable+0x2e4/0x3e8
 kernel_init+0x18/0x110
 ret_from_fork+0x10/0x1c
---[ end trace 05a5e7f1f8d84511 ]---

Revert this commit because the upstream commit d999b622fcfb
("rpmsg: virtio: allocate buffer from parent") is a better solution.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

22/30 [
Author: Loic Pallardy
Email: loic.pallardy@st.com
Subject: rpmsg: virtio: allocate buffer from parent
Date: Thu, 10 Jan 2019 14:50:51 +0100

commit d999b622fcfb392aa549e7e56f6f777b09748ea1 upstream

Remoteproc is now capable to create one specific sub-device per
virtio link to associate a dedicated memory pool.
This implies to change device used by virtio_rpmsg for
buffer allocation from grand-parent to parent.

Signed-off-by: Loic Pallardy <loic.pallardy@st.com>
Reviewed-by: Anup Patel <anup@brainfault.org>
Tested-by: Anup Patel <anup@brainfault.org>
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>
]

23/30 [
Author: Uma Shankar
Email: uma.shankar@intel.com
Subject: drm: add missing part for SDK patch of HDR support
Date: Wed, 31 May 2017 15:40:49 +0530

This patch is the missing part of the SDK patch ("drm: Add
HDR source metadata property").

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

24/30 [
Author: Song Bing
Email: bing.song@nxp.com
Subject: MLK-18834 ion: Enable ion on Kernel 4.14
Date: Tue, 10 Jul 2018 17:36:06 -0700

commit f14c444263c259be0d44c31a0b8a700741ac3686 from
https://source.codeaurora.org/external/imx/linux-imx.git

Enable ion driver on Linux platform for Kernel 4.14.

Signed-off-by: Song Bing <bing.song@nxp.com>
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

25/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: media:imx8: take s/g_parm to new interface
Date: Tue, 9 Apr 2019 09:58:25 +0800

In upstream commit 4471109e3894 ("media: convert g/s_parm to
g/s_frame_interval in subdevs"), g/s_parm should be converted
to g/s_frame_interval.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

26/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: drm/bridge: adv7511: fix adv7535 DSI-HDMI converter malfunction issue
Date: Thu, 9 May 2019 16:14:17 +0800

1. When picking up the patch from SDK, there is typo (adv7511->addr_edid)
which cause compile error.
2. The function "adv7511_init_cec_regmap" should be called after the register
ADV7511_REG_CEC_I2C_ADDR is initialised with proper value.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

27/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: mxc: vpu: fix compile warning
Date: Thu, 9 May 2019 18:31:07 +0800

./include/linux/kernel.h:852:39: warning: comparison between ‘enum <anonymous>’ and ‘enum <anonymous>’ [-Wenum-compare]
 #define max(x, y) __careful_cmp(x, y, >)
                                       ^
./include/linux/kernel.h:828:30: note: in definition of macro ‘__cmp’
 #define __cmp(x, y, op) ((x) op (y) ? (x) : (y))
                              ^~
./include/linux/kernel.h:852:19: note: in expansion of macro ‘__careful_cmp’
 #define max(x, y) __careful_cmp(x, y, >)
                   ^~~~~~~~~~~~~
drivers/mxc/vpu-encoder-b0/vpu_encoder_b0.c:3535:10: note: in expansion of macro ‘max’
  count = max(GTB_ENC_CMD_RESERVED, VID_API_ENC_EVENT_RESERVED);
          ^~~

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

28/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: usb: typec: use new enum typec_port_type variables
Date: Fri, 10 May 2019 10:35:03 +0800

Because of upstream commit ceeb162500c3 ("usb: typec: Separate the definitions
for data and power roles"), enum typec_port_type has changes as below:
		TYPEC_PORT_DFP -> TYPEC_PORT_SRC
		TYPEC_PORT_UFP -> TYPEC_PORT_SNK

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

29/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: staging: typec: tcpci: fix complie error because of max_snk_mv/ma/mw
Date: Wed, 10 Apr 2019 14:10:26 +0800

Because of upstream commit e8374db15436 ("usb: typec: tcpm: remove max_snk_mv/ma/mw"),
remove all max_snk_mv/ma/mw.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

30/30 [
Author: Quanyang Wang
Email: quanyang.wang@windriver.com
Subject: staging: typec: tcpci: fix compile error because of modification of struct tcpci
Date: Wed, 10 Apr 2019 14:41:30 +0800

Because of upstream commit 8f9439022648 ("staging: typec: handle vendor
defined part and modify drp toggling flow"), "struct i2c_client *client"
is not in "struct tcpci" anymore, so change tcpci->client->irq to
to_i2c_client(dev)->irq, and client->dev to dev.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>