btrfs: tree-checker: use %zu format string for size_t
Issue: LIN10-6898

1/1 [
Author: Arnd Bergmann
Email: arnd@arndb.de
Subject: btrfs: tree-checker: use %zu format string for size_t
Date: Wed, 6 Dec 2017 15:18:14 +0100

The return value of sizeof() is of type size_t, so we must print it
using the %z format modifier rather than %l to avoid this warning
on some architectures:

fs/btrfs/tree-checker.c: In function 'check_dir_item':
fs/btrfs/tree-checker.c:273:50: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'u32' {aka 'unsigned int'} [-Werror=format=]

Fixes: 005887f2e3e0 ("btrfs: tree-checker: Add checker for dir item")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: David Sterba <dsterba@suse.com>
Signed-off-by: David Sterba <dsterba@suse.com>
Signed-off-by: De Huo <de.huo@windriver.com>
]
Signed-off-by: Yue Tao <Yue.Tao@windriver.com>