fs: yaffs2: replace CURRENT_TIME by other appropriate apis
1/2 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: fs: yaffs2: replace CURRENT_TIME by other appropriate apis
Date: Fri, 25 Aug 2017 14:58:34 +0800

The macro CURRENT_TIME has already been deleted by commit bfe1c566453a
("time: delete CURRENT_TIME_SEC and CURRENT_TIME"). So we need to
replace all the uses of CURRENT_TIME by current_time() for filesystem
times, and ktime_get_* function for others.

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

2/2 [
Author: Kevin Hao
Email: kexin.hao@windriver.com
Subject: fs: yaffs2: includes the missing header file
Date: Fri, 25 Aug 2017 14:58:35 +0800

To fix the following build error:
  fs/yaffs2/yaffs_vfs.c: In function 'yaffs_mknod':
  fs/yaffs2/yaffs_vfs.c:1252:2: error: implicit declaration of function 'current_fsuid' [-Werror=implicit-function-declaration]
    uid_t uid = YCRED_FSUID();
    ^

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>