perf: x86-32: explicitly include <errno.h>
1/1 [
Author: Bruce Ashfield
Email: bruce.ashfield@windriver.com
Subject: perf: x86-32: explicitly include <errno.h>
Date: Mon, 21 Aug 2017 13:52:53 -0400

The 32bit x86 perf build does not find the system definitions of error
return values, hence we end up with:

| In file included from util/libunwind/x86_32.c:32:0:
| util/libunwind/../../arch/x86/util/unwind-libunwind.c: In function 'libunwind__x86_reg_id':
| util/libunwind/../../arch/x86/util/unwind-libunwind.c:109:11: error: 'EINVAL' undeclared (first use in this function); did you mean 'UNW_EINVAL'?
|    return -EINVAL;
|            ^~~~~~
|            UNW_EINVAL

By explicitly including errno.h, we can fix this build without impacting
other architectures.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>