nxp-ls1043: remove no-map attribute for reserved memory
Issue: LIN1018-3639

1/4 [
Author: Yinbo Zhu
Email: yinbo.zhu@nxp.com
Subject: Revert "usb: DWC3: fix usb cause crash issue"
Date: Wed, 26 Sep 2018 10:50:36 +0800

This reverts commit 27f327f7e2033d1cd54853cfba3861cc64466491.

This is to avoid below USB disk issue:
usb 1-1: reset high-speed USB device number 2 using xhci-hcd
sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x6 [current]
sd 2:0:0:0: [sdb] tag#0 ASC=0x28 ASCQ=0x0
sd 2:0:0:0: [sdb] tag#0 CDB: opcode=0x28 28 00 00 00 00 00 00 00 08 00
print_req_error: I/O error, dev sdb, sector 0
Buffer I/O error on dev sdb, logical block 0, async page read
 sdb: unable to read partition table

Signed-off-by: Yinbo Zhu <yinbo.zhu@nxp.com>
[Xulin: Original patch taken from NXP LSDK-18.12, add with
issue information.]
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

2/4 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: arm64: dts: define big endian of IFC NOR for LS1043a
Date: Mon, 25 Mar 2019 16:42:06 +0800

Integrated flash controller present of NOR in LS1043A is big endian.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

3/4 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: Revert "Revert "arm64: Allocate elfcorehdr & crashkernel mem before any reservation""
Date: Tue, 2 Apr 2019 15:07:54 +0800

This reverts commit 2d39a9d746d036ff997c9a7523a2ababface0634.
NXP LS1043A needs to allocate crashkernel memory before reserve the mem.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

4/4 [
Author: Xulin Sun
Email: xulin.sun@windriver.com
Subject: nxp-ls1043: remove no-map attribute for reserved memory
Date: Mon, 1 Apr 2019 15:57:58 +0800

When performing kexec, qman/bman driver need access reserved memory to
determine device state in second kernel. So remove no-map attributes to
allow kernel access those area.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
]

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>